[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "Interlink"
dynamic=["version"]
dependencies = [
  "Flask>=3.1.0",
  "mysql>=0.0.3",
  "mysqlclient>=2.2.7",
  "mysql-connector>=2.2.9",
]
requires-python = ">=3.0"
authors = [
  {name = "Joe Corso"}, 
  {email = "pads.email.address@gmail.com"}
]
description = "Interlink will generate a form and report for any table in a database. It will also create the urls, and the navigation bar."
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE.md", content-type = "text/markdown"}  # or license = {file = "LICENSE.txt"} for legacy declaration
#license-files = ["LICEN[CS]E.*"]
keywords = ["flask", "form", "report", "navigation", "url", "sql", "database"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://github.com/padsRepo/interlink"
Documentation = "https://github.com/padsRepo/interlink/wiki/Interlink.html"
Repository = "https://github.com/padsRepo/interlink.git"

[tool.setuptools.dynamic]
version = {attr = "interlink.__version__"}

[tool.setuptools.packages.find]
where = ["src"]  # or wherever your package code is located

[tool.setuptools.package-data]
"interlink" = ["formulator/*", "safeHaven/*", "toolkit/*", "templeton/templates/*", "templeton/templates/guide/*"]
#"Bug Tracker" = "https://github.com/me/spam/issues"
#Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

#[project.scripts]
#spam-cli = "spam:main_cli"
